version: '3.8'
services:
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gestion_equipe
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: nestjs_backend
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://user:password@database:5432/gestion_equipe
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run start:dev

volumes:
  postgres_data:
